# 會員登入帳號
account = "0966961001"

# 會員登入密碼
password = "prwr29hx"

# 訂位餐廳
# 響食天堂 1 , 饗饗 2, 旭集 10
res = "2"

# 訂位區域
# 重要!!! 請參考訂位系統上區域顯示的文字填入，請勿填錯，否則會訂位失敗
city = "台北市"

# 訂位人數
# 重要!!! 每間餐廳訂位上限人數不同，請務必確認好上限人數，請勿填錯，否則會訂位失敗
people = "8"

# 訂位日期
# 重要!!! 填入的日期要在餐廳允許的訂位時間內，請勿填錯，否則會訂位失敗
bookingDate = "2022-01-22"

# 餐次
# 午餐，下午餐，晚餐
mealTime = "午餐"

# 店別
# 重要!!! 請參考訂位系統上店別顯示的文字填入，請勿填錯，否則會訂位失敗
store = "微風店"

# 進場時段
# 重要!!! 請參考訂位系統上有開放的進場時段顯示的文字填入，請勿填錯，否則會訂位失敗
time = "11:30"

# 素食人數
vegetable = "0"

# 兒童座椅
childChair = "0"